language: python
cache: pip
python:
  - "2.7.11"

before_install:
  - export DJANGO_SETTINGS_MODULE=kikar_hamedina.settings
  - export PYTHONPATH=$PYTHONPATH:$HOME/build/agamrafaeli/kikar-hamedina/kikar_hamedina

install: "pip install -r requirements/base.txt"

services: postgresql

before_script:
  # Prepare DB
  - psql -c "CREATE DATABASE travisci;" -U postgres
  - python kikar_hamedina/manage.py migrate
  - python kikar_hamedina/manage.py loaddata fixture data_fixture_mks.json --app mks

  # Run server
  - python kikar_hamedina/manage.py runserver localhost:8000 &
  - sleep 3
script:
  - nosetests

after_script:
  - coveralls